language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install pylint"
# command to run tests
script:
    - 1
after_success:
    - echo "Success"
after_failure:
    - echo "Failure"
notifications:
  email: false
